# Generated by Django 4.1.4 on 2022-12-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
