# Generated by Django 4.1.4 on 2023-01-26 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0003_alter_post_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asnwer', to='querys.answerpost'),
        ),
    ]
