# Generated by Django 4.1.4 on 2023-01-26 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0005_rename_post_answerpost_post_from_remove_post_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerpost',
            old_name='post_from',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='answer_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_post', to='querys.answerpost'),
        ),
    ]
