# Generated by Django 4.1.4 on 2023-01-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0006_rename_post_from_answerpost_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='querys.answerpost'),
        ),
    ]
