# Generated by Django 4.1.4 on 2023-01-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0007_alter_post_answer_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answer_post',
        ),
    ]
