# Generated by Django 4.1.4 on 2023-02-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0008_remove_post_answer_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='descriptions',
        ),
    ]
