# Generated by Django 4.1.4 on 2023-02-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0009_rename_post_post_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='querys.answerpost'),
        ),
    ]
