# Generated by Django 4.1.4 on 2023-02-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0010_post_answer_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answer_post',
        ),
        migrations.AlterField(
            model_name='answerpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='querys.post'),
        ),
    ]
