# Generated by Django 4.1.4 on 2022-12-29 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0002_patients_email_patients_name_patients_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='name',
        ),
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='describe_your_problems',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='patients',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PatientAppointmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine_one', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine_two', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine_three', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine_others', models.CharField(blank=True, max_length=500, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('medicine_eating_time', multiselectfield.db.fields.MultiSelectField(choices=[('Before Breakfast', 'Before Breakfast'), ('After Breakfast', 'After Breakfast'), ('Before Lunch', 'Before Lunch'), ('After Lunch', 'After Lunch'), ('Before Dinner', 'Before Dinner'), ('After Dinner', 'After Dinner')], max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.patients')),
            ],
        ),
    ]
