# Generated by Django 4.1.4 on 2023-02-08 17:06

import ambulance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_patients_name_patients_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=ambulance.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
    ]
