# Generated by Django 4.1.4 on 2023-02-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_department_name_alter_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
