# Generated by Django 4.1.4 on 2023-02-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_patients_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientappointmentanswer',
            options={'verbose_name': 'Patient Appointment Answer'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name': 'Appointment'},
        ),
    ]
