# Generated by Django 4.1.4 on 2022-12-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorsignup_rename_patient_patientsignup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsignup',
            options={'verbose_name_plural': 'Doctors Accounts'},
        ),
        migrations.AlterModelOptions(
            name='patientsignup',
            options={'verbose_name_plural': 'Patients Accounts'},
        ),
    ]
