# Generated by Django 4.1.4 on 2023-02-14 10:14

import ambulance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctorsignup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsignup',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorsignup',
            name='phone',
            field=ambulance.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='patientsignup',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientsignup',
            name='phone',
            field=ambulance.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, null=True, region=None),
        ),
    ]
