# Generated by Django 4.1.4 on 2023-02-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctorsignup_email_doctorsignup_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsignup',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientsignup',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
