# Generated by Django 4.1.3 on 2022-11-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('department', models.CharField(choices=[('CARDIOLOGY', 'CARDIOLOGY'), ('NEUROLOGY', 'NEUROLOGY'), ('ORTHOPEDICS', 'ORTHOPEDICS'), ('CANCER DEPARTMENT', 'CANCER DEPARTMENT'), ('OPHTHALMOLOGY', 'OPHTHALMOLOGY'), ('RESPIRATORY', 'RESPIRATORY')], max_length=21)),
                ('describe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Get_touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
