# Generated by Django 4.1.3 on 2022-11-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='createquery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
