# Generated by Django 4.1.4 on 2023-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_delete_ambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
