# Generated by Django 4.1.4 on 2023-02-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
