# Generated by Django 4.1.4 on 2022-12-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_email', models.EmailField(max_length=50)),
                ('driver_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='ambulances')),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance_hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.ambulance')),
            ],
        ),
    ]
