# Generated by Django 4.1.4 on 2023-02-08 16:52

import ambulance.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='driver_number',
            field=ambulance.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='ambulance_hire',
            name='number',
            field=ambulance.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
    ]
