# Generated by Django 4.1.4 on 2023-02-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0003_alter_ambulance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance_hire',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
