# Generated by Django 4.1.4 on 2023-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0004_ambulance_hire_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance_hire',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
