# Generated by Django 4.1.4 on 2023-02-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0005_alter_ambulance_hire_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambulance_hire',
            options={'verbose_name': 'Ambulance hire'},
        ),
    ]
